[build]
target = "wasm32-unknown-unknown"
rustflags = ["-Ctarget-feature=-sign-ext", "-Clink-arg=-s", "-Ctarget-cpu=mvp", "-Cpanic=abort"]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[alias]
bw = "build --target wasm32-unknown-unknown --lib"
